[package]
name = "TradeStream"
version = "0.1.0"
edition = "2024"

[dependencies]
MarketDataFeed = { path = "../MarketDataFeed" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }